apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
  name: nginx-ingress
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
  name: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress
subjects:
  - kind: ServiceAccount
    name: nginx-ingress
    namespace: '{{ .Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/component: controller
  name: nginx-ingress
# können wir die folgenden Regeln als ServiceAccount in der dogu.json abbilden?
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/component: controller
  name: nginx-ingress
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/component: controller
  name: nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress
subjects:
  - kind: ServiceAccount
    name: nginx-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/component: controller
  finalizers:
    - "cloudogu.com/nginx-tcp-services"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  labels:
    app: ces
    dogu.name: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app.kubernetes.io/component: controller
  finalizers:
    - "cloudogu.com/nginx-udp-services"
---
# Configmap for the general nginx-ingress-controller configuration
# see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
apiVersion: v1
data:
  proxy-set-headers: "{{ .Namespace }}/nginx-ingress-custom-headers"
kind: ConfigMap
metadata:
  name: nginx-ingress
---
# Configmap for adding custom headers before sending traffic to backends
# see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-set-headers
apiVersion: v1
data:
  # Disable gzip encoding for proxy applications, so that the response can be processed by subfilters
  Accept-Encoding: "identity"
kind: ConfigMap
metadata:
  name: nginx-ingress-custom-headers
